### ISSUE TITLE
[Spell] Feral Druid-Rip

### ISSUE THREAD

**Issue by Alexandechz** [mrss2707/VFireWoW-BFA#6]
Khi dùng với 5 point thấy Bleed không được 24s mà tầm 5s còn thấp hơn khi dùng 1 point 
![image](https://github.com/mrss2707/VFireWoW-BFA/assets/142685961/99444bb5-7c87-4541-8054-42901dc558b3)

**Comment by mrss2707** [comment]
Fixed
